---
services:
  avnav:
    image: xfreex/avnav-daily:latest
    container_name: avnav
    restart: unless-stopped
    privileged: true
    user: 1000:1000
    network_mode: host
    volumes:
      - /dev:/dev
      - ./avnav:/var/lib/avnav
    ports:
      - 8080:8080
      - 8082:8082
    environment: 
      - UID=1000
      - GID=1000


